apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-nurse-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mk-nurse
  template:
    metadata:
      labels:
        app: mk-nurse
    spec:
      containers:
        - name: mk-nurse
          image: gammaspeck/mk-nurse
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URL
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER_ID
              value: mockstagram

            - name: REDIS_HOST
              value: redis-srv
